### ISSUE TITLE
Optimization of Lambda in computeApicobasal.m fails

### ISSUE THREAD

**Issue by lisapankewitz** [KIT-IBT/Cobiveco#2]
Hi,
thanks so much for providing this amazing tools.
For some meshes, I encounter the issue that `lambda` in `computeApicobasal.m` cannot be optimized, which sometimes can lead to an error in the following function using `pcg `which is not converging and hence generation of the apicobasal coordinate is failing.
I wanted to ask, if you have a hint for a better initial guess for `lambda`, to improve the optimization or another idea for a default value to fall back to.
I checked different thresholds and  increased the number of iterations for the optimization but without any luck.
Maybe you have encountered that issue before or have a better guess.

Thanks so much for your time and have a nice day!

Below is the code snipped I am referring to:

```
% half-width at half-maximum of the point spread function of the operator
% inv(speye(size(L))+lambda*(L'*L))
hwhm = mean(abLength)/100;
lambda = 1.58*hwhm^3.57;
lambda = numel(abSmoothCl)/numel(ab)*lambda;
fprintf('\n0\t%.3e\n', lambda);

b = M'*abSmoothCl + eta*E'*baseVal;
MM = M'*M + eta*(E'*E);
LL = L'*L;
extrapMisfit = o.cfg.abExtrapSmooth/100;

try
    [~,flag,iter] = secant(@objFun, 1e-1*lambda, lambda, 1e-2*extrapMisfit);
    if flag
        warning('Secant stopped at iteration %i without converging.', iter);
    end
catch err
    disp(getReport(err, 'extended', 'hyperlinks', 'off'));
    warning('Optimization of lambda failed. Using default value instead.');
    objFun(lambda);
endcomputeApicobasal.m
```

**Comment by axel-loewe** [comment]
Hi,

Computing `lambda` is indeed a tricky point which can fail. However, the `try/catch` block should prevent the program from breaking by proceeding with the initial value.
Does the problem occur later on in the code when proceeding with the initial value?

If the issue is not solved by now, we could look into it if you provide an example to reproduce the problem.

Sorry for the late response, we didn't have notifications enabled for new issues.
