### ISSUE TITLE
example_CibivecoX.m missing example files

### ISSUE THREAD

**Issue by jab0707** [KIT-IBT/Cobiveco#6]
It looks like the example_CobivecoX.m example script is missing the required/expected geometry files. In the script the following is set as the setup for cobivecox:

in Cobiveco\examples\example_CobivecoX.m:
```matlab
% c = cobiveco(struct('inPrefix','geo2/geo2', 'outPrefix','result_geo2/', 'exportLevel',3));
c = cobiveco(struct('inPrefix','meanTOF/meanTOF', 'outPrefix','result_meanTOF/', 'exportLevel',3, 'maxit', 4000));
```
The commented line referring to geo2 would likely not work as geo2 is missing definitions of the valves, needed for cobivecoX. The second line which looks for "meanTOF/meanTOF" results in an error because there is no meanTOF folder int he examples directory.

The main problem I am having is that I wanted to find an example definition of each of the inputs for cobivecoX so I could replicate it with my own models. It is not clear how the valves need to be defined. Should the valve.vtu files include just the ring of the valve annulus? Can it be a surface of the valve plane? I figure these questions would be answered if I had a working cobivecoX example.

Thanks for your help!

-Jake Bergquist
[jbergquist@sci.utah.edu](mailto:jbergquist@sci.utah.edu)

**Comment by lisapankewitz** [comment]
Hi @jab0707 ,

and thanks again for your issue!

Since the data is too big, I had it on a pre-release repository on zenodo until I have a final doi.
I just pushed the [data repository address to the github repository](https://github.com/lisapankewitz/Cobiveco) so the address will be included in the KIT repository with the next pull request.

For brevity,  the zenodo doi is the following [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7922601.svg)](https://doi.org/10.5281/zenodo.7922601) and the record can be found[here](https://doi.org/10.5281/zenodo.7922601
).

Let me know, if you have any other questions :)


Have a great day!

**Comment by axel-loewe** [comment]
Fixed with https://github.com/KIT-IBT/Cobiveco/commit/d2c21d4cccbb67f61937393b22d183ee5434b98b
